import {
  Inbox,
  Star,
  Send,
  FileText,
  Trash2,
  Users,
  Bell,
  MessagesSquare,
  ShoppingBag,
  Tag,
  type LucideIcon,
} from "lucide-react";

export type FolderId =
  | "inbox"
  | "starred"
  | "sent"
  | "drafts"
  | "trash"
  | "social"
  | "updates"
  | "forums"
  | "shopping"
  | "promotions";

export type MailboxFolderId = Exclude<FolderId, "starred">;

export type FolderGroup = "primary" | "category";

export interface FolderConfig {
  id: FolderId;
  label: string;
  icon: LucideIcon;
  group: FolderGroup;
}

export const folders: FolderConfig[] = [
  { id: "inbox", label: "Inbox", icon: Inbox, group: "primary" },
  { id: "starred", label: "Starred", icon: Star, group: "primary" },
  { id: "sent", label: "Sent", icon: Send, group: "primary" },
  { id: "drafts", label: "Drafts", icon: FileText, group: "primary" },
  { id: "trash", label: "Trash", icon: Trash2, group: "primary" },
  { id: "social", label: "Social", icon: Users, group: "category" },
  { id: "updates", label: "Updates", icon: Bell, group: "category" },
  { id: "forums", label: "Forums", icon: MessagesSquare, group: "category" },
  { id: "shopping", label: "Shopping", icon: ShoppingBag, group: "category" },
  { id: "promotions", label: "Promotions", icon: Tag, group: "category" },
];

export interface Email {
  id: string;
  folder: MailboxFolderId;
  senderName: string;
  senderEmail: string;
  initials: string;
  subject: string;
  preview: string;
  body: string[];
  time: string;
  fullDate: string;
  read: boolean;
  starred: boolean;
}

export const initialEmails: Email[] = [
  {
    id: "mail-1",
    folder: "inbox",
    senderName: "Layla Brennan",
    senderEmail: "layla.brennan@northfieldstudio.com",
    initials: "LB",
    subject: "Updated brand guidelines are ready for review",
    preview: "I've attached the revised color palette and typography scale for the Q3 refresh.",
    body: [
      "Hi there,",
      "I've attached the revised color palette and typography scale for the Q3 refresh. The main change is a slightly warmer neutral tone across the surface colors, plus a new condensed weight for headings.",
      "Could you take a look before Thursday's sync? I'd love to lock this in before we brief the rest of the team.",
      "Thanks,\nLayla",
    ],
    time: "9:41 AM",
    fullDate: "Wed, Sep 2, 2026, 9:41 AM",
    read: false,
    starred: true,
  },
  {
    id: "mail-2",
    folder: "inbox",
    senderName: "Marcus Ueda",
    senderEmail: "marcus.ueda@brightloop.io",
    initials: "MU",
    subject: "Re: Sprint 24 retro notes",
    preview: "Thanks for pulling this together — a couple of small additions below.",
    body: [
      "Thanks for pulling this together — a couple of small additions below.",
      "1. We should track the flaky checkout test as its own action item.\n2. Let's add a note about the onboarding survey response rate.",
      "Otherwise this looks great, nice summary.",
    ],
    time: "8:55 AM",
    fullDate: "Wed, Sep 2, 2026, 8:55 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-3",
    folder: "inbox",
    senderName: "Priya Chandrasekaran",
    senderEmail: "priya.c@harborworks.com",
    initials: "PC",
    subject: "Invoice #4471 is now overdue",
    preview: "Just a friendly reminder that invoice #4471 for $2,400 was due last week.",
    body: [
      "Hi,",
      "Just a friendly reminder that invoice #4471 for $2,400 was due last week. Let me know if you need a copy resent or if there's anything blocking payment on your end.",
      "Best,\nPriya",
    ],
    time: "7:30 AM",
    fullDate: "Wed, Sep 2, 2026, 7:30 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-4",
    folder: "inbox",
    senderName: "Noah Petrov",
    senderEmail: "noah@petrovconsulting.dev",
    initials: "NP",
    subject: "Quick question about the API rate limits",
    preview: "Are the new rate limits documented anywhere yet, or is 100 req/min still accurate?",
    body: [
      "Hey,",
      "Are the new rate limits documented anywhere yet, or is 100 req/min still accurate for the public API? We're planning a batch job and want to make sure we don't get throttled.",
      "Cheers,\nNoah",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 6:12 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-5",
    folder: "inbox",
    senderName: "Camille Fournier",
    senderEmail: "camille.fournier@atlaslogistics.com",
    initials: "CF",
    subject: "Warehouse migration timeline",
    preview: "Attaching the revised cutover schedule — we've pushed the go-live to the 18th.",
    body: [
      "Hi team,",
      "Attaching the revised cutover schedule — we've pushed the go-live to the 18th to give the integration team more buffer.",
      "Please flag anything that conflicts with existing commitments.",
      "Camille",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 3:47 PM",
    read: true,
    starred: true,
  },
  {
    id: "mail-6",
    folder: "inbox",
    senderName: "Deacon Whitfield",
    senderEmail: "deacon.w@cinderpeakgames.com",
    initials: "DW",
    subject: "Playtest feedback is in",
    preview: "Overall really positive — the pacing in level 3 is the main sticking point.",
    body: [
      "Hey,",
      "Overall really positive — the pacing in level 3 is the main sticking point, a few testers felt it dragged after the mid-boss.",
      "Full notes are in the shared doc. Let's discuss at standup.",
    ],
    time: "Mon",
    fullDate: "Mon, Aug 31, 2026, 11:05 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-7",
    folder: "inbox",
    senderName: "Simone Achebe",
    senderEmail: "simone.achebe@greenfieldhr.com",
    initials: "SA",
    subject: "Reminder: benefits enrollment closes Friday",
    preview: "You still have a few plan options to confirm before the enrollment window closes.",
    body: [
      "Hello,",
      "You still have a few plan options to confirm before the enrollment window closes this Friday at 5 PM.",
      "Reach out if you have any questions about coverage tiers.",
      "Simone, People Ops",
    ],
    time: "Mon",
    fullDate: "Mon, Aug 31, 2026, 9:00 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-8",
    folder: "inbox",
    senderName: "Théo Lindqvist",
    senderEmail: "theo.lindqvist@northfieldstudio.com",
    initials: "TL",
    subject: "Server maintenance window this weekend",
    preview: "We'll be taking staging down for about two hours on Saturday morning.",
    body: [
      "Hi all,",
      "We'll be taking staging down for about two hours on Saturday morning (9–11 AM) to apply database patches.",
      "Production is unaffected. Ping me if that overlaps with anything important.",
    ],
    time: "Sun",
    fullDate: "Sun, Aug 30, 2026, 4:20 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-9",
    folder: "inbox",
    senderName: "Renata Costa",
    senderEmail: "renata.costa@harborworks.com",
    initials: "RC",
    subject: "Contract renewal — a few redlines",
    preview: "Legal sent back the MSA with three small redlines, nothing structural.",
    body: [
      "Hi,",
      "Legal sent back the MSA with three small redlines, nothing structural — mostly clarifying the SLA language in section 4.",
      "Redlined copy attached. Let me know if these work for you.",
      "Renata",
    ],
    time: "Sat",
    fullDate: "Sat, Aug 29, 2026, 1:15 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-10",
    folder: "inbox",
    senderName: "Owen Kavanagh",
    senderEmail: "owen.kavanagh@brightloop.io",
    initials: "OK",
    subject: "Design system icons — final pass",
    preview: "Swapped out the last few inconsistent stroke widths, ready for handoff.",
    body: [
      "Hey,",
      "Swapped out the last few inconsistent stroke widths, ready for handoff whenever engineering wants to pull the new set.",
      "Exported as SVG sprite and individual files, both in the shared drive.",
    ],
    time: "Fri",
    fullDate: "Fri, Aug 28, 2026, 10:40 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-11",
    folder: "inbox",
    senderName: "Ingrid Solberg",
    senderEmail: "ingrid.solberg@atlaslogistics.com",
    initials: "IS",
    subject: "Q3 planning doc — add your section",
    preview: "Please fill in your team's goals by end of week so we can circulate a draft.",
    body: [
      "Hi everyone,",
      "Please fill in your team's goals by end of week so we can circulate a draft before the leadership offsite.",
      "Template and examples are linked at the top of the doc.",
      "Thanks,\nIngrid",
    ],
    time: "Thu",
    fullDate: "Thu, Aug 27, 2026, 2:30 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-12",
    folder: "inbox",
    senderName: "Felix Amaro",
    senderEmail: "felix.amaro@cinderpeakgames.com",
    initials: "FA",
    subject: "Welcome to the beta program",
    preview: "You're in! Here's everything you need to get started with the closed beta.",
    body: [
      "Welcome aboard,",
      "You're in! Here's everything you need to get started with the closed beta, including the download link and feedback form.",
      "We'll send patch notes every Friday. Have fun, and thanks for helping us test.",
    ],
    time: "Aug 24",
    fullDate: "Mon, Aug 24, 2026, 8:00 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-13",
    folder: "sent",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Re: Updated brand guidelines are ready for review",
    preview: "Looks great — one small note on the heading weight, otherwise approved.",
    body: [
      "Hi Layla,",
      "Looks great — one small note on the heading weight for the condensed style, it feels a touch heavy at smaller sizes. Otherwise approved from my side.",
      "Thanks for the quick turnaround.",
    ],
    time: "9:58 AM",
    fullDate: "Wed, Sep 2, 2026, 9:58 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-14",
    folder: "sent",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Follow-up: warehouse migration timeline",
    preview: "The 18th works fine on our end, thanks for the heads up.",
    body: [
      "Hi Camille,",
      "The 18th works fine on our end, thanks for the heads up. We'll adjust the integration test schedule accordingly.",
      "Let us know if the date shifts again.",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 4:05 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-15",
    folder: "sent",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Redlines look good",
    preview: "Reviewed the MSA changes, section 4 language works for us.",
    body: [
      "Hi Renata,",
      "Reviewed the MSA changes, section 4 language works for us. Sending the countersigned copy back today.",
      "Thanks for handling this quickly.",
    ],
    time: "Sat",
    fullDate: "Sat, Aug 29, 2026, 2:50 PM",
    read: true,
    starred: true,
  },
  {
    id: "mail-16",
    folder: "sent",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Re: Playtest feedback is in",
    preview: "Agreed on level 3 pacing, let's scope a fix for next sprint.",
    body: [
      "Hey Deacon,",
      "Agreed on level 3 pacing, let's scope a fix for next sprint. Could you tag the specific encounters that felt slow?",
      "Will bring it up at standup too.",
    ],
    time: "Mon",
    fullDate: "Mon, Aug 31, 2026, 11:40 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-17",
    folder: "sent",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Q3 goals — draft",
    preview: "Added our section to the planning doc, feedback welcome.",
    body: [
      "Hi Ingrid,",
      "Added our section to the planning doc, feedback welcome before Friday.",
      "Happy to hop on a call if anything needs more context.",
    ],
    time: "Thu",
    fullDate: "Thu, Aug 27, 2026, 3:15 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-18",
    folder: "drafts",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Notes from the vendor call",
    preview: "Draft — need to fill in the pricing comparison table before sending.",
    body: [
      "Hi team,",
      "Draft — need to fill in the pricing comparison table before sending. Summary of the call so far:",
      "- Vendor confirmed a 30-day trial\n- Support SLA is 4 hours for critical issues\n- Pricing tiers still pending confirmation",
    ],
    time: "10:12 AM",
    fullDate: "Wed, Sep 2, 2026, 10:12 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-19",
    folder: "drafts",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Onboarding checklist for new hires",
    preview: "Draft — still need input from IT on the equipment section.",
    body: [
      "Hi Simone,",
      "Draft — still need input from IT on the equipment section before this is ready to share with managers.",
      "Will follow up once I hear back.",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 1:30 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-20",
    folder: "drafts",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Beta feedback summary",
    preview: "Draft — collecting themes from the first week of beta reports.",
    body: [
      "Hi Felix,",
      "Draft — collecting themes from the first week of beta reports before sending a summary to the wider team.",
      "So far performance on lower-end hardware is the most common thread.",
    ],
    time: "Fri",
    fullDate: "Fri, Aug 28, 2026, 5:05 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-21",
    folder: "drafts",
    senderName: "You",
    senderEmail: "faham.mohammed@xantory.com",
    initials: "YO",
    subject: "Re: API rate limits",
    preview: "Draft — need to confirm the new limit with the platform team first.",
    body: [
      "Hi Noah,",
      "Draft — need to confirm the new limit with the platform team first, will get back to you by end of day.",
    ],
    time: "Wed",
    fullDate: "Wed, Aug 26, 2026, 8:45 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-22",
    folder: "trash",
    senderName: "Bulk Deals Weekly",
    senderEmail: "offers@bulkdealsweekly.example",
    initials: "BD",
    subject: "Your exclusive discount expires tonight",
    preview: "Don't miss out — 40% off sitewide for the next few hours only.",
    body: [
      "Don't miss out — 40% off sitewide for the next few hours only.",
      "Shop now before the timer runs out.",
    ],
    time: "Mon",
    fullDate: "Mon, Aug 31, 2026, 6:00 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-23",
    folder: "trash",
    senderName: "Automated Reports",
    senderEmail: "noreply@harborworks.com",
    initials: "AR",
    subject: "Your weekly usage summary",
    preview: "Here's a summary of activity across your workspace for last week.",
    body: [
      "Here's a summary of activity across your workspace for last week.",
      "12 tasks completed, 3 new comments, 1 pending approval.",
    ],
    time: "Sun",
    fullDate: "Sun, Aug 30, 2026, 7:00 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-24",
    folder: "trash",
    senderName: "Community Newsletter",
    senderEmail: "digest@cinderpeakgames.com",
    initials: "CN",
    subject: "This month in the community",
    preview: "Fan art highlights, patch notes recap, and an upcoming AMA.",
    body: [
      "Fan art highlights, patch notes recap, and an upcoming AMA with the design team.",
      "Read the full digest on the community hub.",
    ],
    time: "Aug 20",
    fullDate: "Thu, Aug 20, 2026, 9:00 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-25",
    folder: "social",
    senderName: "Pulse",
    senderEmail: "notifications@pulse.example",
    initials: "PU",
    subject: "Aiko Tanaka commented on your post",
    preview: "\"This is such a great breakdown, thanks for sharing!\"",
    body: [
      "Aiko Tanaka commented on your post:",
      "\"This is such a great breakdown, thanks for sharing!\"",
      "Reply to keep the conversation going.",
    ],
    time: "10:20 AM",
    fullDate: "Wed, Sep 2, 2026, 10:20 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-26",
    folder: "social",
    senderName: "Pulse",
    senderEmail: "notifications@pulse.example",
    initials: "PU",
    subject: "You have 3 new connection requests",
    preview: "See who wants to connect with you this week.",
    body: [
      "You have 3 new connection requests waiting.",
      "Review and accept them from your network page.",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 5:45 PM",
    read: false,
    starred: false,
  },
  {
    id: "mail-27",
    folder: "social",
    senderName: "Meridian Circle",
    senderEmail: "updates@meridiancircle.example",
    initials: "MC",
    subject: "Your post is getting attention",
    preview: "Your recent post has reached 200 views and counting.",
    body: [
      "Your recent post has reached 200 views and counting.",
      "Keep the momentum going with a follow-up update.",
    ],
    time: "Mon",
    fullDate: "Mon, Aug 31, 2026, 1:10 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-28",
    folder: "updates",
    senderName: "Vantage Cloud",
    senderEmail: "updates@vantagecloud.example",
    initials: "VC",
    subject: "Your monthly billing statement is ready",
    preview: "Your September statement is now available to download.",
    body: [
      "Your September statement is now available to download from your account.",
      "No action is needed if your payment method is up to date.",
    ],
    time: "9:05 AM",
    fullDate: "Wed, Sep 2, 2026, 9:05 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-29",
    folder: "updates",
    senderName: "Northfield IT",
    senderEmail: "it-updates@northfieldstudio.com",
    initials: "NI",
    subject: "Password policy changes effective next week",
    preview: "Minimum password length is increasing to 14 characters.",
    body: [
      "Starting next week, the minimum password length is increasing to 14 characters.",
      "You'll be prompted to update your password on your next login.",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 11:00 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-30",
    folder: "updates",
    senderName: "BrightLoop Status",
    senderEmail: "status@brightloop.io",
    initials: "BS",
    subject: "Scheduled maintenance completed",
    preview: "All systems are back to normal after tonight's maintenance window.",
    body: [
      "All systems are back to normal after tonight's maintenance window.",
      "No further action is required.",
    ],
    time: "Sun",
    fullDate: "Sun, Aug 30, 2026, 2:00 AM",
    read: true,
    starred: false,
  },
  {
    id: "mail-31",
    folder: "forums",
    senderName: "DevCircle Forum",
    senderEmail: "forum@devcircle.example",
    initials: "DF",
    subject: "New reply to your thread: Caching strategies",
    preview: "Someone replied to your post in the Backend category.",
    body: [
      "Someone replied to your post \"Caching strategies for read-heavy APIs\" in the Backend category.",
      "View the thread to keep the discussion going.",
    ],
    time: "8:15 AM",
    fullDate: "Wed, Sep 2, 2026, 8:15 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-32",
    folder: "forums",
    senderName: "Cinderpeak Community",
    senderEmail: "forum@cinderpeakgames.com",
    initials: "CC",
    subject: "Someone quoted your post",
    preview: "Your comment on the playtest thread was quoted by another member.",
    body: [
      "Your comment on the playtest thread was quoted by another member.",
      "Check out the discussion in the beta feedback forum.",
    ],
    time: "Fri",
    fullDate: "Fri, Aug 28, 2026, 4:35 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-33",
    folder: "shopping",
    senderName: "Northfield Supply Co.",
    senderEmail: "orders@northfieldsupply.example",
    initials: "NS",
    subject: "Your order has shipped",
    preview: "Order #58213 is on its way and should arrive by Friday.",
    body: [
      "Order #58213 is on its way and should arrive by Friday.",
      "Track your package using the link in your account.",
    ],
    time: "7:50 AM",
    fullDate: "Wed, Sep 2, 2026, 7:50 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-34",
    folder: "shopping",
    senderName: "Atlas Office Goods",
    senderEmail: "receipts@atlasofficegoods.example",
    initials: "AO",
    subject: "Receipt for your recent purchase",
    preview: "Thanks for your order — here's a copy of your receipt.",
    body: [
      "Thanks for your order — here's a copy of your receipt for your records.",
      "Reach out to support if anything looks off.",
    ],
    time: "Thu",
    fullDate: "Thu, Aug 27, 2026, 6:20 PM",
    read: true,
    starred: false,
  },
  {
    id: "mail-35",
    folder: "promotions",
    senderName: "BrightLoop Deals",
    senderEmail: "deals@brightloop.io",
    initials: "BD",
    subject: "Save 20% on your next annual plan",
    preview: "Switch to annual billing this week and save 20%.",
    body: [
      "Switch to annual billing this week and save 20% off your subscription.",
      "Offer ends Sunday at midnight.",
    ],
    time: "6:30 AM",
    fullDate: "Wed, Sep 2, 2026, 6:30 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-36",
    folder: "promotions",
    senderName: "Harborworks Marketplace",
    senderEmail: "promo@harborworks.com",
    initials: "HM",
    subject: "New arrivals this week",
    preview: "Check out what's new in the marketplace this week.",
    body: [
      "Check out what's new in the marketplace this week, hand-picked for your team.",
      "Browse the full catalog online.",
    ],
    time: "Yesterday",
    fullDate: "Tue, Sep 1, 2026, 9:15 AM",
    read: false,
    starred: false,
  },
  {
    id: "mail-37",
    folder: "promotions",
    senderName: "Cinderpeak Games Store",
    senderEmail: "store@cinderpeakgames.com",
    initials: "CG",
    subject: "Weekend sale: 30% off DLC",
    preview: "All expansion packs are 30% off through Sunday.",
    body: [
      "All expansion packs are 30% off through Sunday.",
      "Grab yours before the sale ends.",
    ],
    time: "Sat",
    fullDate: "Sat, Aug 29, 2026, 10:00 AM",
    read: true,
    starred: false,
  },
];
