import type { Plan, Role, User, UserStatus } from "./types";

export const roles: Role[] = ["Admin", "Editor", "Member", "Viewer"];

export const roleStyles: Record<Role, string> = {
  Admin: "bg-violet-500/10 text-violet-600 dark:text-violet-400",
  Editor: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
  Member: "bg-secondary text-secondary-foreground",
  Viewer: "bg-muted text-muted-foreground",
};

export const plans: Plan[] = ["Free", "Pro", "Enterprise"];

export const planStyles: Record<Plan, string> = {
  Free: "bg-muted text-muted-foreground",
  Pro: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
  Enterprise: "bg-violet-500/10 text-violet-600 dark:text-violet-400",
};

export const statusStyles: Record<UserStatus, string> = {
  Active: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-500",
  Invited: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
  Suspended: "bg-destructive/10 text-destructive",
};

/** Country names prefixed with their flag emoji, used as the default for new invites. */
export const countries: string[] = [
  "🇺🇸 United States",
  "🇬🇧 United Kingdom",
  "🇮🇳 India",
  "🇧🇷 Brazil",
  "🇰🇷 South Korea",
  "🇬🇧 United Kingdom",
  "🇪🇸 Spain",
  "🇦🇪 United Arab Emirates",
  "🇹🇷 Turkey",
  "🇵🇹 Portugal",
  "🇺🇸 United States",
  "🇳🇬 Nigeria",
  "🇸🇪 Sweden",
  "🇰🇷 South Korea",
  "🇨🇦 Canada",
  "🇲🇽 Mexico",
  "🇯🇵 Japan",
  "🇩🇪 Germany",
  "🇫🇷 France",
  "🇦🇺 Australia",
];

export const initialUsers: User[] = [
  {
    id: "user-1",
    name: "Evelyn Carter",
    email: "evelyn.carter@northwind.com",
    role: "Admin",
    plan: "Enterprise",
    country: "🇺🇸 United States",
    status: "Active",
  },
  {
    id: "user-2",
    name: "Marcus Webb",
    email: "marcus.webb@northwind.com",
    role: "Editor",
    plan: "Pro",
    country: "🇬🇧 United Kingdom",
    status: "Active",
  },
  {
    id: "user-3",
    name: "Priya Nair",
    email: "priya.nair@northwind.com",
    role: "Member",
    plan: "Pro",
    country: "🇮🇳 India",
    status: "Active",
  },
  {
    id: "user-4",
    name: "Diego Alvarez",
    email: "diego.alvarez@northwind.com",
    role: "Member",
    plan: "Free",
    country: "🇧🇷 Brazil",
    status: "Invited",
  },
  {
    id: "user-5",
    name: "Hannah Kim",
    email: "hannah.kim@northwind.com",
    role: "Viewer",
    plan: "Free",
    country: "🇰🇷 South Korea",
    status: "Active",
  },
  {
    id: "user-6",
    name: "Oliver Bennett",
    email: "oliver.bennett@northwind.com",
    role: "Editor",
    plan: "Pro",
    country: "🇬🇧 United Kingdom",
    status: "Suspended",
  },
  {
    id: "user-7",
    name: "Zara Ahmed",
    email: "zara.ahmed@northwind.com",
    role: "Member",
    plan: "Enterprise",
    country: "🇦🇪 United Arab Emirates",
    status: "Active",
  },
  {
    id: "user-8",
    name: "Lucas Ferreira",
    email: "lucas.ferreira@northwind.com",
    role: "Admin",
    plan: "Enterprise",
    country: "🇵🇹 Portugal",
    status: "Active",
  },
  {
    id: "user-9",
    name: "Grace Whitfield",
    email: "grace.whitfield@northwind.com",
    role: "Viewer",
    plan: "Free",
    country: "🇺🇸 United States",
    status: "Invited",
  },
  {
    id: "user-10",
    name: "Noah Park",
    email: "noah.park@northwind.com",
    role: "Member",
    plan: "Pro",
    country: "🇰🇷 South Korea",
    status: "Active",
  },
  {
    id: "user-11",
    name: "Amara Okafor",
    email: "amara.okafor@northwind.com",
    role: "Member",
    plan: "Free",
    country: "🇳🇬 Nigeria",
    status: "Active",
  },
  {
    id: "user-12",
    name: "Elias Johansson",
    email: "elias.johansson@northwind.com",
    role: "Editor",
    plan: "Pro",
    country: "🇸🇪 Sweden",
    status: "Active",
  },
  {
    id: "user-13",
    name: "Isabella Rossi",
    email: "isabella.rossi@northwind.com",
    role: "Viewer",
    plan: "Free",
    country: "🇪🇸 Spain",
    status: "Suspended",
  },
  {
    id: "user-14",
    name: "Ethan Brooks",
    email: "ethan.brooks@northwind.com",
    role: "Member",
    plan: "Pro",
    country: "🇨🇦 Canada",
    status: "Active",
  },
  {
    id: "user-15",
    name: "Sofia Martinez",
    email: "sofia.martinez@northwind.com",
    role: "Admin",
    plan: "Enterprise",
    country: "🇲🇽 Mexico",
    status: "Active",
  },
  {
    id: "user-16",
    name: "Kenji Tanaka",
    email: "kenji.tanaka@northwind.com",
    role: "Editor",
    plan: "Pro",
    country: "🇯🇵 Japan",
    status: "Invited",
  },
  {
    id: "user-17",
    name: "Lena Schmidt",
    email: "lena.schmidt@northwind.com",
    role: "Member",
    plan: "Free",
    country: "🇩🇪 Germany",
    status: "Active",
  },
  {
    id: "user-18",
    name: "Camille Dubois",
    email: "camille.dubois@northwind.com",
    role: "Viewer",
    plan: "Free",
    country: "🇫🇷 France",
    status: "Active",
  },
  {
    id: "user-19",
    name: "Jack Sullivan",
    email: "jack.sullivan@northwind.com",
    role: "Member",
    plan: "Pro",
    country: "🇦🇺 Australia",
    status: "Active",
  },
  {
    id: "user-20",
    name: "Fatima Al-Sayed",
    email: "fatima.alsayed@northwind.com",
    role: "Admin",
    plan: "Enterprise",
    country: "🇦🇪 United Arab Emirates",
    status: "Active",
  },
];
